# Generated by Django 4.0.3 on 2023-12-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_bidding_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bid_start',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
