# Generated by Django 4.0.3 on 2023-12-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_bidding_bid_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='bid_start',
            new_name='bid_Start',
        ),
    ]
